apiVersion: v1
kind: Service
metadata: 
  name: commingsoon-page
  namespace: commingsoon
spec: 
  selector:
    app: commingsoon-page
    # ClusterIP (default)
    # LoadBalancer (wors on cloud)
    # NodePort (most used)
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80