services:
   db:
     image: mysql:latest
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: 123
       MYSQL_DATABASE: db
       MYSQL_USER: dbuser
       MYSQL_PASSWORD: 123

   postfixadmin:
     depends_on:
       - db
     image: postfixadmin:latest
     ports:
       - "8888:80"
     restart: always
     environment:
       POSTFIXADMIN_DB_TYPE: mysqli
       POSTFIXADMIN_DB_HOST: db
       POSTFIXADMIN_DB_USER: dbuser
       POSTFIXADMIN_DB_NAME: db
       POSTFIXADMIN_DB_PASSWORD: 123
       POSTFIXADMIN_SMTP_SERVER: postfix
       POSTFIXADMIN_SMTP_PORT: 25
       POSTFIXADMIN_ENCRYPT: md5crypt
